### ISSUE TITLE
Support for Docker Compose plugin

### ISSUE THREAD

**Issue by felixoi** [mailcow/mailcow-ansiblerole#35]
Currently this role only supports the docker-compose standalone version. The Docker plugin version is installed automatically in the installation script as described https://docs.mailcow.email/i_u_m/i_u_m_install/#docker-compose these days. This role should at least support the Docker plugin version as of this.

@ntimo Your account is the only one which commited to this repo as part of the mailcow org. Could you clarify the term "The official ansible role" from the "About Me" section of this repository? I've the feeling that some things here are not up to date. I'd be happy to help out but would like to know how this role is handled currently. Looking at the repo only, it feels more like community-supported and not "official".

**Comment by ntimo** [comment]
@felixoi We for sure can change the role to use the "docker compose" command instead of "docker-compose". Or build some kind of auto detection for what the user has installed on the server. Honestly I was not aware that the mailcow project now suggests to use `docker compose` since before it for sure was docker-compose and thats why the role uses that. 

Well the role is basically the "official" mailcow Ansible role. I am currently maintaing it, but I was a little bit bussy lately and had no real time to check the issues/mr's here. If you would like to help out by submitting MR's that would be greatly appreciated.

**Comment by sebix** [comment]
I'm also confused which docker-compose variant to install.

The readme says, docker ce and `docker-compose` is required. So do I need https://download.docker.com/linux/debian in the apt sources and  install `docker-compose-plugin`? Or just docker from Debian's repos and the package `docker-compose`?

**Comment by felixoi** [comment]
@sebix `docker-compose-plugin` is the docker plugin version. Currently for this Ansible role you need the standalone version.
